config/routes.rb
Chowheroes::Application.routes.draw do

  root :to => 'users#new'

  post "twilio/" => "twilio#create"
  get "twilio/callback" => "twilio#callback"
  
  resources :users
  resources :donations
  resources :sessions, :only => ['create', 'destroy']

  

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :donations

  attr_accessor :password, :username, :email, :password_confirmation

#  validates :email,    :format     => { :with => /@/ }, :on => :create
  validates :username, :presence   => true,             :uniqueness => true
  validates :email,    :uniqueness => true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def show

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by_username(params[:username])
    if user && user.password == params[:password]
    	session[:id] = user.id
    	redirect_to user
    else
    	redirect_to '/', :flash => { :error => 'Invalid username or password' }
    end
  end

  def destroy
    sessions.clear
    redirect_to '/'
  end
end

app/controllers/twilio_controller.rb
require 'modules/twilio'

class TwilioController < ApplicationController
  def create
    @client ||= Twilio.client
    Twilio.message(
            :client => @client, 
            :to => "+16502231243", 
            :body => Twilio::Messages::TEST)
    render :nothing => true, :status => :ok
  end

  def callback
    Rails.debug.logger params
    render :nothing => true, :status => :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = ActionController::Parameters.new(params[:user])
    user_params.permit!
    user = User.new(user_params)
    user.save
    redirect_to user
  end

  def show
    @user = User.find(session[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chowheroes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.haml
%h1 Chow Heroes!

- if flash[:error]
  .error
    %p= flash[:error]

%h2 Sign Up
.sign_up_form
  = form_for @user  do |f|
    = f.label :email
    = h f.email_field :email, :required => true
    %br
    = f.label :username
    = h f.text_field :username, :required => true
    %br
    = f.label :password
    = f.password_field :password, :required => true
    %br
    = f.label :password_confirmation
    = h f.password_field :password_confirmation, :required => true
    %br
    = f.submit 'Submit'

%h2 Log In
.login_form
  = form_tag sessions_path do
    = label_tag :username
    = h text_field_tag :username
    %br
    = label_tag :password
    = h password_field_tag :password
    %br 
    = submit_tag 'Submit' 